academy = input("შეიყვანე აკადემია: ")
school = input("შეიყვანე სკოლა: ")
name = input("შეიყვანე სახელი: ")
last_name = input("შეიყვანე გვარი: ")
age = input("შეიყვანე ასაკი: ")
print(academy)
print(school)
print(name)
print(last_name)
print(age)